### ISSUE TITLE
Drop Monocle dependency on core

### ISSUE THREAD

**Issue by Fristi** [nuttycom/xenomorph#7]
I would suggest to keep the API as simple as possible. I know optics compose well and are well define abstractions, but for some users of your library it might be daunting. Therefore I would suggest to just use functions in the core. You could add a module which adds some additional combinators which uses the optics.

**Comment by nuttycom** [comment]
That seems reasonable.

**Comment by Fristi** [comment]
No shared excitement for this feature and I don't have a need for it as well.
